### PR TITLE
Corrected Semantics

### PR DESCRIPTION
**Pull request by FoxMoss**
You did not create a proxy. Rhodium is the proxy, Slate is the interface or frontend. Fact checked via https://en.wikipedia.org/wiki/Proxy_server.

### CODE REVIEW

**Comment by Tacogamerman** [comment]
I know, but proxy just sounds so much better in a sentence 😭😭😭😭

**Comment by Tacogamerman** [comment]
Also wtf is a semantic lmfao

**Comment by Tacogamerman** [comment]
Anyways I’ll fix

**Comment by Tacogamerman** [comment]
But you gotta admit, even though it isn’t correct, proxy just sounds cleaner in a sentence.

**Comment by FoxMoss** [comment]
> "I'll fix" 
> closes PR.

mate, i fixed it for you

**Comment by jessiejs** [comment]
Open this and merge it. LGTM.

**Comment by jessiejs** [comment]
oh nvm its fixed

**Comment by Tacogamerman** [comment]
> `>` "I'll fix" `>` closes PR.
> 
> mate, i fixed it for you

I had already edited the readme after I saw the Pr, but I did fix it.

**Comment by Tacogamerman** [comment]
If I had merged it it would have deleted some progress

**Comment by Tacogamerman** [comment]
@FoxMoss But thanks

**Pull request closed without merging**
